use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    // Re-run this build script if the data file changes
    println!("cargo:rerun-if-changed=data/conway_polynomials.txt");

    let src = fs::read_to_string("data/conway_polynomials.txt")
        .expect("could not read data/conway_polynomials.txt");

    let entries = parse_conway_table(&src);

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("conway_table.rs");
    let mut out = fs::File::create(&dest).unwrap();

    write_table(&mut out, &entries).unwrap();
}

/// One entry from the Conway polynomial table.
struct Entry {
    p: u64,
    n: u64,
    coeffs: Vec<u64>,
}

fn parse_conway_table(src: &str) -> Vec<Entry> {
    // Find the content between the outermost `[` and the trailing `0]`
    // Each inner entry looks like: [p,n,[c0,c1,...,cn]]
    let mut entries = Vec::new();

    for line in src.lines() {
        let line = line.trim();

        // Skip the wrapper line, the sentinel `0]`, and blank lines
        if line.is_empty()
            || line == "allConwayPolynomials := ["
            || line.starts_with("0]")
        {
            continue;
        }

        // Strip a trailing comma if present
        let line = line.trim_end_matches(',');

        // Each entry is `[p,n,[c0,c1,...]]`
        // Strip the outer brackets
        let line = line
            .strip_prefix('[')
            .and_then(|s| s.strip_suffix(']'))
            .expect("expected entry wrapped in [ ]");

        // Split into at most 3 parts on the first two commas before the inner `[`
        // Format: p,n,[coeffs]
        let bracket = line.find('[').expect("expected inner coefficient list");
        let pn_part = &line[..bracket]; // "p,n,"
        let coeff_part = &line[bracket..]; // "[c0,c1,...]"

        let mut pn = pn_part.trim_end_matches(',').splitn(2, ',');
        let p: u64 = pn.next().unwrap().trim().parse().expect("bad p");
        let n: u64 = pn.next().unwrap().trim().parse().expect("bad n");

        // Strip brackets from coefficient list
        let coeff_part = coeff_part
            .strip_prefix('[')
            .and_then(|s| s.strip_suffix(']'))
            .expect("expected coefficients wrapped in [ ]");

        let coeffs: Vec<u64> = coeff_part
            .split(',')
            .map(|s| s.trim().parse().expect("bad coefficient"))
            .collect();

        entries.push(Entry { p, n, coeffs });
    }

    // Guarantee sorted order for binary search at runtime
    entries.sort_by_key(|e| (e.p, e.n));
    entries
}

fn write_table(out: &mut fs::File, entries: &[Entry]) -> std::io::Result<()> {
    // Total number of entries
    writeln!(out, "// Auto-generated by build.rs. Do not edit.")?;
    writeln!(out, "// Coefficients are in ascending degree order.")?;
    writeln!(out)?;

    // Write each coefficient slice as a named static so the main array can
    // hold `&'static [u64]` references.
    for (i, e) in entries.iter().enumerate() {
        write!(out, "static COEFFS_{i}: &[u64] = &[")?;
        for (j, c) in e.coeffs.iter().enumerate() {
            if j > 0 { write!(out, ", ")?; }
            write!(out, "{c}")?;
        }
        writeln!(out, "];")?;
    }

    writeln!(out)?;

    // Main table: sorted array of (p, n, coeffs)
    writeln!(
        out,
        "static CONWAY_TABLE: &[(u64, u64, &[u64])] = &["
    )?;
    for (i, e) in entries.iter().enumerate() {
        writeln!(out, "    ({}, {}, COEFFS_{i}),", e.p, e.n)?;
    }
    writeln!(out, "];")?;

    writeln!(out)?;

    Ok(())
}